# Generated by Django 2.2.2 on 2019-06-20 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('total_t', models.FloatField(max_length=50)),
                ('total_f', models.FloatField(max_length=50)),
                ('percentaje_t', models.FloatField(max_length=50)),
                ('percentaje_f', models.FloatField(max_length=50)),
                ('date_analysis', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('n_workers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('D1', 'Dominio 1'), ('D2', 'Dominio 2'), ('D3', 'Dominio 3'), ('D4', 'Dominio 4'), ('D5', 'Dominio 5'), ('D6', 'Dominio 6'), ('D7', 'Dominio 7'), ('D8', 'Dominio 8'), ('D9', 'Dominio 9'), ('D10', 'Dominio 10'), ('D11', 'Dominio 11')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('AD1', 'Administrador 1'), ('AD2', 'Administrador 2'), ('GG', 'Gerente General'), ('VR', 'Vendedor')], max_length=3)),
                ('status', models.BooleanField()),
                ('initial', models.DateField()),
                ('finish', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Empresa')),
                ('usuario_personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Empresa')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Question')),
                ('usuario_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Personal')),
            ],
            options={
                'unique_together': {('question', 'usuario_choice')},
            },
        ),
    ]
