# Generated by Django 2.2.2 on 2019-06-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
