# Generated by Django 2.2.2 on 2019-06-21 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='choice',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Questions.Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
