# Generated by Django 2.2.2 on 2019-06-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_auto_20190621_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.BooleanField(default=None),
        ),
    ]
