# Generated by Django 2.2.2 on 2019-06-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20190621_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
