# Generated by Django 2.2.2 on 2019-06-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_auto_20190621_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
